require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('../models/Category');
const Product = require('../models/Product');

const categories = [
  { slug: 'white', name: 'Makrana White', colorBase: '#EDEAE1', colorVein: '#B9AF9C' },
  { slug: 'beige', name: 'Kishangarh Beige', colorBase: '#DCC9A6', colorVein: '#9C7B4B' },
  { slug: 'black', name: 'Indian Black', colorBase: '#2B2926', colorVein: '#B08D57' },
  { slug: 'onyx', name: 'Green Onyx', colorBase: '#3B5C4A', colorVein: '#8FB89A' },
  { slug: 'granite', name: 'Rajasthan Granite', colorBase: '#4A4642', colorVein: '#8A8478' },
  { slug: 'sandstone', name: 'Red Sandstone', colorBase: '#8C3A2B', colorVein: '#C98F72' },
];

const products = [
  { name: 'Makrana Statuario White', category: 'white', origin: 'Makrana, Rajasthan', thickness: '18mm / 20mm', finish: 'Polished', description: "Makrana marble is the same white stone quarried for the Taj Mahal and countless temples across India, and this Statuario grade is our finest cut of it — a fine, tight grain with soft grey veining that photographs almost pure white. It's the grade architects specify for main living-room flooring, formal staircases, and cladding in high-end residences and hotel lobbies. Because Makrana marble doesn't fade or yellow with age the way many imported whites do, it remains the standard choice for buyers who want flooring that still looks new after twenty years. Available for both new construction and renovation projects; ask for a quote with your exact square footage for accurate pricing per sq ft." },
  { name: 'Makrana Albeta White', category: 'white', origin: 'Makrana, Rajasthan', thickness: '18mm', finish: 'Polished', description: "A more accessible grade of Makrana white marble with clearly visible veining, Albeta is the go-to choice for buyers who want genuine Makrana stone without paying Statuario-grade prices. It's widely used for full-house flooring in villas and apartments across Rajasthan, Gujarat and Delhi NCR, and holds up well in both residential and light-commercial settings. If you're comparing Makrana marble price per square foot across grades, Albeta typically sits in the mid-range — a practical balance of authenticity, appearance and budget for large-format flooring projects." },
  { name: 'Makrana Dungri White', category: 'white', origin: 'Makrana, Rajasthan', thickness: '18mm', finish: 'Polished / Honed', description: "Dungri is a cooler, brighter white than Albeta with tighter, more uniform veining — a common choice for temple flooring, marble inlay work, and pooja rooms where a clean, bright surface matters. It's also popular with contractors doing bulk orders for religious trusts and community halls across Rajasthan, since it offers genuine Makrana quality at a lower price point than the premium Statuario grade. Available in both polished and honed finish depending on whether you want a glossy or matte surface." },
  { name: 'Ambaji White Marble', category: 'white', origin: 'Ambaji, near Rajasthan border', thickness: '18mm / 20mm', finish: 'Polished', description: "Sourced from Ambaji, just across the Rajasthan-Gujarat border, this is the most budget-friendly genuine white marble in our catalog. It's a popular pick for buyers comparing marble prices for full-home flooring who want a bright white look without the cost of Makrana-grade stone. Commonly used across Rajasthan, Gujarat and Madhya Pradesh for residential flooring, staircases and wall cladding in mid-range construction projects. Bulk quantities available — request a quote for wholesale pricing on large orders." },
  { name: 'Kishangarh Ivory Beige', category: 'beige', origin: 'Kishangarh, Rajasthan', thickness: '18mm', finish: 'Polished / Honed', description: "Processed at Asia's largest marble market in Kishangarh, this warm, consistent beige marble is one of the most-ordered stones in the Indian flooring trade. Its even tone makes it easy to lay across large areas without visible seams or color mismatch — a common complaint with more heavily-veined stones. Popular for entire-home flooring, corridors, and commercial spaces like showrooms and offices where a warm, neutral floor is wanted. Available in both polished (glossy) and honed (matte) finish; ask us about current wholesale rates per square foot." },
  { name: 'Kishangarh Sangemarmar', category: 'beige', origin: 'Kishangarh, Rajasthan', thickness: '18mm / 20mm', finish: 'Polished', description: "A fine-grained beige-white marble with subtle striations, Sangemarmar is a mid-range staple across Rajasthan's marble trade — the kind of stone dealers keep in stock year-round because it sells steadily to both homeowners and builders. It suits flooring, staircases and wall panelling equally well, and its balanced tone works in both traditional and contemporary interiors. Good option if you want something with a bit more visual texture than plain Ivory Beige, at a similar price point." },
  { name: 'Bidasar Beige Marble', category: 'beige', origin: 'Bidasar, Rajasthan', thickness: '18mm', finish: 'Polished', description: "A softer, sandy beige tone with faint cream veining, Bidasar marble is commonly specified for villa flooring across Jaipur and Jodhpur where builders want a warm, earthy floor color that pairs well with wooden furniture and warm lighting. It's one of the more affordable marble options in our catalog while still being genuine natural stone rather than composite or engineered marble — a point worth knowing if you're comparing natural vs artificial marble for your project." },
  { name: 'Rajnagar Black Marble', category: 'black', origin: 'Rajnagar, Rajasthan', thickness: '20mm', finish: 'Polished', description: "Deep black marble with fine gold-brass veining, finished to a high gloss that catches light beautifully on feature walls and reception counters. This is one of our premium stones — commonly requested for hotel lobbies, corporate reception desks, and luxury residential feature walls where a striking black-and-gold contrast is wanted. Also used for inlay borders alongside white Makrana marble in traditional Rajasthani flooring patterns. Given the price point, most buyers order this for accent areas rather than full-room flooring." },
  { name: 'Kotputli Black Marble', category: 'black', origin: 'Kotputli, Rajasthan', thickness: '20mm', finish: 'Polished', description: "A denser, more matte-leaning black marble than Rajnagar, Kotputli holds a sharper edge under cutting and polishing — which is why fabricators often choose it for staircases, skirting, and door/window frames where crisp, clean edges matter more than maximum shine. A practical, slightly more affordable alternative to Rajnagar black for buyers who want the black-marble look across a larger area of their project." },
  { name: 'Udaipur Green Onyx', category: 'onyx', origin: 'Udaipur, Rajasthan', thickness: '20mm', finish: 'Polished, backlit-ready', description: "Translucent green onyx cut thin enough to be backlit, letting light pass through and reveal the stone's natural banding pattern — a dramatic, one-of-a-kind effect that photographs beautifully. This is a specialty stone requested for bar counters, reception desks, spa walls, and feature panels in high-end hospitality and residential projects across India. Because each slab's veining is unique, we recommend viewing photos of the actual slab before ordering for a specific feature installation — contact us with your project details." },
  { name: 'Rajsamand Honey Onyx', category: 'onyx', origin: 'Rajsamand, Rajasthan', thickness: '20mm', finish: 'Polished, backlit-ready', description: "Warm amber-honey onyx with dramatic natural banding, this is a signature stone for hotel lobbies, spa reception areas, and statement feature niches where clients want something visually unforgettable. Like our green onyx, it's typically cut for backlighting to bring out the depth of the banding pattern. Sourced from Rajsamand, close to our own base of operations, so we can often arrange site visits to view slabs in person before you commit to a large order." },
  { name: 'Jalore Granite Grey', category: 'granite', origin: 'Jalore, Rajasthan', thickness: '18mm', finish: 'Flamed / Polished', description: "Hard-wearing grey granite from the Jalore belt, one of India's major granite-producing regions. Granite's scratch and heat resistance make it the standard choice for kitchen countertops, staircases, and high-traffic flooring in both homes and commercial spaces — areas where marble would show wear faster. Available in flamed finish (textured, slip-resistant, good for outdoor steps and pathways) or polished finish (smooth, glossy, for indoor counters and floors)." },
  { name: 'Jhansi Red Granite', category: 'granite', origin: 'Jalore belt, Rajasthan', thickness: '18mm', finish: 'Polished', description: "A speckled red-and-black granite popular for kitchen platforms, boundary walls, and monument work. Its fine, consistent speckle pattern makes it forgiving of daily kitchen use — stains and scratches are far less visible than on plain-colored stones. A solid mid-range granite option for buyers who want more visual character than plain grey granite at a similar price point." },
  { name: 'Rajasthan Black Galaxy', category: 'granite', origin: 'Jalore, Rajasthan', thickness: '18mm / 20mm', finish: 'Polished', description: "Black granite flecked with fine gold-colored mineral particles that catch light like a starfield — this is one of the most internationally recognized granite varieties from the Rajasthan belt, exported worldwide for premium kitchen countertops and commercial cladding. If you've seen 'Black Galaxy granite' listed on international stone marketplaces, this is that same stone, sourced directly rather than through an export intermediary — which is typically reflected in better pricing for bulk buyers." },
  { name: 'Dholpur Red Sandstone', category: 'sandstone', origin: 'Dholpur, Rajasthan', thickness: '25mm', finish: 'Natural / Chiseled', description: "Classic red sandstone, the same stone used across Rajasthan's forts, havelis and government buildings for centuries — instantly recognizable and closely associated with traditional Rajasthani architecture. A warm, textured stone well suited to building facades, garden pathways, boundary walls, and courtyard paving. Natural or hand-chiseled finish gives it a rustic, non-slip surface that's popular for outdoor and heritage-style projects. One of our most affordably priced stones, well suited to large-area outdoor work." },
  { name: 'Jodhpur Chocolate Sandstone', category: 'sandstone', origin: 'Jodhpur, Rajasthan', thickness: '25mm', finish: 'Natural / Sawn', description: "A rich, deep brown sandstone with a coarser natural grain than red sandstone, popular for boundary cladding, courtyard paving, and garden landscaping where a darker, earthier tone is wanted. Sawn finish gives cleaner, straighter edges than natural-split stone, making it easier to lay in regular patterns. A durable outdoor stone that weathers well in Rajasthan's climate." },
  { name: 'Bansi Pink Sandstone', category: 'sandstone', origin: 'Bharatpur, Rajasthan', thickness: '25mm', finish: 'Natural / Chiseled', description: "The soft pink-beige sandstone visible across Jaipur's old city facades and many of Rajasthan's heritage buildings, quarried near Bharatpur. A popular choice for homeowners and architects wanting that recognizable 'Pink City' look for building exteriors, boundary walls, and garden features. Our most affordably priced stone, making it a practical choice for large outdoor areas on a budget." },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected. Seeding...');

  await Category.deleteMany({});
  await Product.deleteMany({});

  await Category.insertMany(categories);
  await Product.insertMany(products);

  console.log(`Seeded ${categories.length} categories and ${products.length} products.`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
