// A practical list, not the full ISO-3166 set - India first since that's
// the primary market, then common export destinations and major countries.
export const COUNTRIES = [
  { name: 'India', iso2: 'IN', dial: '+91' },
  { name: 'United Arab Emirates', iso2: 'AE', dial: '+971' },
  { name: 'Saudi Arabia', iso2: 'SA', dial: '+966' },
  { name: 'Qatar', iso2: 'QA', dial: '+974' },
  { name: 'Oman', iso2: 'OM', dial: '+968' },
  { name: 'Kuwait', iso2: 'KW', dial: '+965' },
  { name: 'Bahrain', iso2: 'BH', dial: '+973' },
  { name: 'United States', iso2: 'US', dial: '+1' },
  { name: 'United Kingdom', iso2: 'GB', dial: '+44' },
  { name: 'Canada', iso2: 'CA', dial: '+1' },
  { name: 'Australia', iso2: 'AU', dial: '+61' },
  { name: 'Singapore', iso2: 'SG', dial: '+65' },
  { name: 'Malaysia', iso2: 'MY', dial: '+60' },
  { name: 'Nepal', iso2: 'NP', dial: '+977' },
  { name: 'Bangladesh', iso2: 'BD', dial: '+880' },
  { name: 'Sri Lanka', iso2: 'LK', dial: '+94' },
  { name: 'Pakistan', iso2: 'PK', dial: '+92' },
  { name: 'China', iso2: 'CN', dial: '+86' },
  { name: 'Germany', iso2: 'DE', dial: '+49' },
  { name: 'France', iso2: 'FR', dial: '+33' },
  { name: 'Italy', iso2: 'IT', dial: '+39' },
  { name: 'Spain', iso2: 'ES', dial: '+34' },
  { name: 'Netherlands', iso2: 'NL', dial: '+31' },
  { name: 'South Africa', iso2: 'ZA', dial: '+27' },
  { name: 'Kenya', iso2: 'KE', dial: '+254' },
  { name: 'Nigeria', iso2: 'NG', dial: '+234' },
  { name: 'Japan', iso2: 'JP', dial: '+81' },
  { name: 'South Korea', iso2: 'KR', dial: '+82' },
  { name: 'Indonesia', iso2: 'ID', dial: '+62' },
  { name: 'Thailand', iso2: 'TH', dial: '+66' },
  { name: 'New Zealand', iso2: 'NZ', dial: '+64' },
  { name: 'Brazil', iso2: 'BR', dial: '+55' },
  { name: 'Mexico', iso2: 'MX', dial: '+52' },
  { name: 'Russia', iso2: 'RU', dial: '+7' },
  { name: 'Turkey', iso2: 'TR', dial: '+90' },
  { name: 'Egypt', iso2: 'EG', dial: '+20' },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // India
